POST http://localhost:3003/api/users HTTP/1.1 
content-type: application/json
//this empty line is required to have

# {
#  "username": "hellas",
#   "name": "Arto Hellas",
#   "password": "salainen"
# }
{
 "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "abcxyz"
}

# {
#  "userId": "6444732aebf2ac3e4580b64a",
#  "url": "http://hhaha",
#  "author": "anhpham",
#  "title": "testing the populate method",
#  "likes": 12
# }